music = {
    "tere liye":"https://www.youtube.com/watch?v=AlvUuGJccKs&list=RDw5VFOKKAbQQ&index=3",
    "no idea":"https://www.youtube.com/watch?v=_r-nPqWGG6c&list=RDnk5wvx_OAnw&index=3",
    "new drop":"https://www.youtube.com/watch?v=Ji8qyyM8GB0&list=RDnk5wvx_OAnw&index=9",
    "let you go":"https://www.youtube.com/watch?v=fXF59UWr-tA&list=RDnk5wvx_OAnw&index=5",
    "party for you":"https://www.youtube.com/watch?v=agu22bqGHto&list=RDnk5wvx_OAnw&index=16",
    "don't even text":"https://www.youtube.com/watch?v=PA04qZ0QYYI&list=RDPA04qZ0QYYI&start_radio=1",
    "are are are":"https://www.youtube.com/watch?v=Anc2cP2iWss&list=RDAnc2cP2iWss&start_radio=1",
    "pal pal":"https://www.youtube.com/watch?v=AbkEmIgJMcU&list=RDnk5wvx_OAnw&index=2",
    "sundari":"https://www.youtube.com/watch?v=WpBn9w-Js_c&list=RDPA04qZ0QYYI&index=2",
    "jhol":"https://www.youtube.com/watch?v=-2RAq5o5pwc&list=RDnk5wvx_OAnw&index=8",
    "thoda aur":"https://www.youtube.com/watch?v=Y_PHGEKKP-Q&list=RDGMEM2j3yRsqu_nuzRLnHd2bMVA&index=5",
    "ransom":"https://www.youtube.com/watch?v=1XzY2ij_vL4&list=RD1XzY2ij_vL4&start_radio=1",
    "mere bina":"https://www.youtube.com/watch?v=XvUSsh3gdO4&list=RDw5VFOKKAbQQ&index=13",
    "sunflower":"https://www.youtube.com/watch?v=ApXoWvfEYVU&list=RDPA04qZ0QYYI&index=28",
    "high on you":"https://www.youtube.com/watch?v=gI1Z4UHg9o0&list=RDPA04qZ0QYYI&index=22",
    "lucid dreams":"https://www.youtube.com/watch?v=mzB1VGEGcSU&list=RD1XzY2ij_vL4&index=3",
    "skechers":"https://www.youtube.com/watch?v=feq6MOg3qpA&list=RD1XzY2ij_vL4&index=2",
    "all girls are the same":"https://www.youtube.com/watch?v=h3EJICKwITw&list=RD1XzY2ij_vL4&index=11",
    "obssesed with you":"https://www.youtube.com/watch?v=oP7KHC129RQ&list=RD1XzY2ij_vL4&index=10",
    "now we are strangers":"https://www.youtube.com/watch?v=CBuIINOwNTw&list=RDCBuIINOwNTw&start_radio=1",
    "tere naina":"https://www.youtube.com/watch?v=GYgnPrmbxH4&list=RDGMEM2j3yRsqu_nuzRLnHd2bMVA&index=3",
    "i love you":"https://www.youtube.com/watch?v=0JLRExeOH-k&list=RDw5VFOKKAbQQ&index=20",
    "tum ho":"https://www.youtube.com/watch?v=gkCKTuR-ECI&list=RDw5VFOKKAbQQ&index=35",
    "pink lips":"https://www.youtube.com/watch?v=w5VFOKKAbQQ&list=RDw5VFOKKAbQQ&start_radio=1",
    "long drive":"https://www.youtube.com/watch?v=frARuVJNpRQ&list=RDfrARuVJNpRQ&start_radio=1",
    "hookah bar":"https://www.youtube.com/watch?v=b4b1cMVZOUU&list=PLSBl1TpBZzI5jrDVn4VNh2elix9Vywm99",
    "girl i need you":"https://www.youtube.com/watch?v=-9fMvHicwLE&list=RD-9fMvHicwLE&start_radio=1",
    "labon ko":"https://www.youtube.com/watch?v=-FP2Cmc7zj4&list=RD-FP2Cmc7zj4&start_radio=1",
    "espresso":"https://www.youtube.com/watch?v=eVli-tstM5E&list=RDeVli-tstM5E&start_radio=1",
    "Jiya Dhadak Dhadak Jaye":"https://www.youtube.com/watch?v=iasxMdSu7Jo&list=RDiasxMdSu7Jo&start_radio=1",
    "aadat":"https://www.youtube.com/watch?v=e5LShHAE03A&list=RDe5LShHAE03A&start_radio=1",
    "kangana tera ni":"https://www.youtube.com/watch?v=tA8h_exda3E&list=RD1XzY2ij_vL4&index=21",
    "suicidal":"https://www.youtube.com/watch?v=sjUHRlfIlN4&list=RD1XzY2ij_vL4&index=16",
    "pink panther":"https://www.youtube.com/watch?v=nk5wvx_OAnw&list=RDnk5wvx_OAnw&start_radio=1",
    "Indecisive":"https://www.youtube.com/watch?v=govmFnFY7oQ&list=RDCBuIINOwNTw&index=2",
    "run":"https://www.youtube.com/shorts/hne-E_Wb2Io"


}